id = "grpgscriptlsp-zed"
name = "grpgscriptlsp"
version = "0.0.1"
schema_version = 1
authors = ["Grian Grian <grianguy32@gmail.com>"]
description = "Provides the GRPGScript LSP in Zed."
repository = "https://github.com/grian32/grpg/"

[language_servers.grpgscriptlsp]
name = "grpgscriptlsp"
languages = ["GRPGScript"]

[grammars.grpgscript]
repository = "https://github.com/grian32/tree-sitter-grpgscript"
rev = "2dffcda0af68b8ec9da775a49355074d35e51114"
